version: '3'

services:
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    restart: unless-stopped
    command: --cleanup --interval 5 
    environment: 
      - DOCKER_API_VERSION=1.52
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ~/.docker/config.json:/config.json
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
      
